#!/bin/sh

echo "Using docker compose to setup sandbox development environment:"
docker-compose up -d
echo "  Done"

echo -n "Waiting for RabbitMQ Container: "
until [ "`curl -s -X GET http://localhost:15672/api/index.html`" ]; do
    echo -n .
    sleep 0.2;
done;
echo "  Ready"

# this may be more annoying than helpful opening windows again and again
# echo "Launching RabbitMQ Management UI"
# chromium-browser http://localhost:15672/
