#!/bin/sh

echo "Using docker compose to setup sandbox development environment:"
if [ ! -d "rabbitmq/log" ]; then
    echo "Creating rabbitmq log directory..."
    mkdir -p rabbitmq/log
fi
if [ ! -w "rabbitmq/log" ] || [ ! -k "rabbitmq/log" ]; then
    echo "Setting world-writable + sticky bit on rabbitmq log directory..."
    sudo chmod a+tw rabbitmq/log
fi

docker-compose up -d

if [ ! "$?" = "0" ]; then
    echo "Could not start RabbitMQ sandbox container, exiting..."
    exit 1
fi
echo "  Done"

echo -n "Waiting for RabbitMQ Container: "
until [ "`curl -s -X GET http://localhost:15672/api/index.html`" ]; do
    echo -n .
    sleep 0.2;
done;
echo "  Ready"

# this may be more annoying than helpful opening windows again and again
# echo "Launching RabbitMQ Management UI"
# chromium-browser http://localhost:15672/
